export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TEST_DISPATCH = 'TEST_DISPATCH';
export const GET_MEETUP = 'GET_MEETUP';
export const GET_ALL_MEETUPS = 'GET_ALL_MEETUPS';